resources:
  containers:
    - container: build1
      image: tidocker.azurecr.io/build1

stages:
- stage: CI
  jobs:
  - job: BuildProduct
    container: build1
    steps:
      - checkout: self
      - script: mkdir cmake-build
      - script: |
          cmake ..
          make
          cp Compiler_Tests artifacts
        workingDirectory: cmake-build
        displayName: Build
      - script: ./Compiler_Tests
        workingDirectory: cmake-build
        displayName: "Run Tests"
