jobs:
- job: BuildProduct
  container:
    image: tidocker.azurecr.io
  steps:
    - checkout: self
    - bash: |
      cmake 
      make
      cp Compiler_Tests artifacts
    displayName: Build   