resources:
  containers:
    - container: build1
      image: tidocker.azurecr.io/build1

stages:
- stage: CI
  jobs:
  - job: BuildProduct
    steps:
      - script: docker login tidocker.azurecr.io --username $(SP_APP_ID) --password $(SP_APP_PASSWORD)
      - checkout: self
        target: build1
      - script: mkdir cmake-build
        target: build1
      - script: |
          cmake ..
          make
          cp Compiler_Tests artifacts
        workingDirectory: cmake-build
        displayName: Build
        target: build1
      - script: ./Compiler_Tests
        workingDirectory: cmake-build
        displayName: "Run Tests"
        target: build1

